package com.chris.tiantian.entity;

/**
 * Created by jianjianhong on 20-1-9
 */
public interface Constant {

    //当前策略ID
    String SP_CURRENT_POLICY = "SP_CURRENT_POLICY";
    //刷新网络数据标志
    String SP_LOADING_POLICY_SIGNAL_NETWORK = "SP_LOADING_POLICY_SIGNAL_NETWORK";

    String SP_LASTTIME_POLICY_SIGNAL_NETWORK = "SP_LASTTIME_POLICY_SIGNAL_NETWORK";
    //刷新本地数据标志
    String SP_LOADING_POLICY_SIGNAL_DATABASE = "SP_LOADING_POLICY_SIGNAL_DATABASE";


    String SP_LOADING_POLICY_NETWORK = "SP_LOADING_POLICY_NETWORK";
    String SP_LASTTIME_POLICY_NETWORK = "SP_LASTTIME_POLICY_NETWORK";
    String SP_LOADING_POLICY_DATABASE = "SP_LOADING_POLICY_DATABASE";
}
